version: '3.8'

services:
  backend:
    build:
      context: ./Techdome-backend
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=ap-south-1                # Use the appropriate region where your EC2 is running
      - EC2_INSTANCE_NAME=Devops_Project    # EC2 instance name
      - DATABASE_URL=mongodb://database:27017/test
    depends_on:
      - database

  frontend:
    build:
      context: ./Techdome-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
